# Generated by Django 5.2.8 on 2025-12-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlitchChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título do Erro')),
                ('image_file', models.ImageField(upload_to='word_glitches/')),
                ('correct_answer', models.CharField(max_length=100, verbose_name='Comando para corrigir')),
            ],
        ),
        migrations.CreateModel(
            name='WordTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=50, verbose_name='Palavra/Comando')),
                ('clue', models.CharField(max_length=255, verbose_name='Dica')),
                ('category', models.CharField(default='Formatação', max_length=50)),
            ],
        ),
    ]
