# Generated by Django 5.2.8 on 2025-12-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.TextField(verbose_name='Cenário do Problema')),
                ('data_preview', models.ImageField(blank=True, upload_to='excel_screens/', verbose_name='Print da Planilha')),
                ('correct_formula', models.CharField(max_length=200, verbose_name='Fórmula Correta')),
                ('accepted_variations', models.TextField(help_text='Separe por vírgula', verbose_name='Variações aceitas')),
                ('difficulty', models.IntegerField(default=1)),
            ],
        ),
    ]
