# Generated by Django 5.2.8 on 2025-12-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Peça')),
                ('description', models.TextField(verbose_name='Função/Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hardware_images/', verbose_name='Foto da Peça')),
                ('difficulty', models.IntegerField(choices=[(1, 'Fácil'), (2, 'Médio'), (3, 'Difícil')], default=1)),
            ],
            options={
                'verbose_name': 'Componente de Hardware',
                'verbose_name_plural': 'Componentes de Hardware',
            },
        ),
    ]
